name: Composer Dependency

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    run_as_composer_dependency:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none

            -   run: |
                    mkdir standalone
                    cd standalone
                    # wait for deploy to packagist
                    sleep 30

            -   run: |
                    cd standalone

                    # run
                    composer require rector/rector-prefixed:@dev --dev
                    vendor/bin/rector --debug
