name: With Symfony Dependency

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    matrix:
        strategy:
            fail-fast: false
            matrix:
                actions:
                    -   symfony_version: 2.8
                    -   symfony_version: 3.4
                    -   symfony_version: 4.4
                    -   symfony_version: 5.1

        name: Install With Symfony ${{ matrix.actions.symfony_version }}
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none

            -   run: |
                    mkdir standalone
                    cd standalone
                    # wait for deploy to packagist
                    sleep 30

            -   run: |
                    cd standalone
                    composer require symfony/console:${{ matrix.actions.symfony_version }} --ansi

                    composer require rector/rector-prefixed:@dev --dev --ansi
                    vendor/bin/rector --debug --ansi
